<?php require_once("includes/header.php"); ?>
<?php require_once("includes/navbar.php"); ?>
<?php require_once("includes/main.php"); ?>
<?php require_once("section-img-mobile.php"); ?>
<?php require_once("section-description.php"); ?>
<?php require_once("section-sc.php"); ?>
<?php require_once("section-experience.php"); ?>
<?php require_once("section-competences.php"); ?>
<?php require_once("section-hobbies.php"); ?>
<?php require_once("includes/footer.php"); ?>
